### ISSUE TITLE
Transformer Class Issues

### ISSUE THREAD

**Issue by ret2xzhao** [cps-vip/cps-cosimulation-env#10]
@connorm16755

Regarding the [Transformer](https://github.com/cps-vip/cps-cosimulation-env/blob/main/device_modeling/src/process_level/transformers/transformer_device.py), here are some issues:

1. The **Transformer** class is defined with an `__init__` constructor that initializes the object with a *name*, *communication protocol*, and *transformer type*. However, the `name` and `communication_protocol` parameters are defined but not used within the constructor.

```py
def __init__(self, name: str, communication_protocol: str, transformer_type: str):
        self.transformer_type = transformer_type
        self.primary_voltage = 0
        self.secondary_voltage = 0
```

2. In the provided code, there are `set_primary_voltage` and `set_secondary_voltage` methods, but they set the voltage to `0` and do not actually set the primary and secondary voltages based on the input parameter. Furthermore, there are inconsistencies in the variable names, with `primary_voltage` and `input_voltage` as well as `secondary_voltage` and `output_voltage`.

```py
def set_primary_voltage(self, voltage):
        self.input_voltage = 0

def set_secondary_voltage(self, voltage):
        self.output_voltage = 0
```

3. The `get_turns_ratio` method seems to rely on a `self.taps` list that is not defined in the `__init__` constructor.

```py
def get_turns_ratio(self):
        return self.taps[self.tap_position]
```

**Comment by connor16755** [comment]
Done
